j21/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/secret', to: 'static_pages#secret_page'

  get '/signup',  to: 'users#new'
  resources :users

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

j21/app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :username,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

    class << self
      # Returns the hash digest of the given string.
      def digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
      end

      # Returns a random token.
      def new_token
        SecureRandom.urlsafe_base64
      end
    end
  
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

j21/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

j21/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)

  	if user && user.authenticate(params[:session][:password])

  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		flash[:success] = "Bienvenue sur ton profil !"

  		redirect_to user
  	else
  		flash.now[:danger] = "Combinaison email/mot de passe incorrect.."
  		render "new"
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to login_path
  end
end

j21/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	include ApplicationHelper
	before_action :require_login, only: [:secret_page]
  def home
  end

  def secret_page
  end

end

j21/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    log_in @user
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

j21/app/helpers/application_helper.rb
module ApplicationHelper
	def require_login
	    unless logged_in?
	      flash[:warning] = "Tu dois être logé pour avoir la réponse a la grande question"
	      redirect_to login_path
    	end
  	end
end

j21/app/helpers/sessions_helper.rb
module SessionsHelper

	 # Logs in the given user.
	def log_in(user)
		session[:user_id] = user.id
	end

     # Remembers a user in a persistent session.
    def remember(user)
      user.remember
      cookies.permanent.signed[:user_id] = user.id
      cookies.permanent[:remember_token] = user.remember_token
    end


  # Returns the user corresponding to the remember token cookie.
    def current_user
      if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
      elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(cookies[:remember_token])
          log_in user
          @current_user = user
        end
      end
    end

	 # Returns true if the user is logged in, false otherwise.
	def logged_in?
    	!current_user.nil?
    end

  	 # Forgets a persistent session.
    def forget(user)
      user.forget
      cookies.delete(:user_id)
      cookies.delete(:remember_token)
    end

     # Logs out the current user.
    def log_out
    	forget(current_user)
    	session.delete(:user_id)
    	@current_user = nil
    end
end

j21/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "All Users", users_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

j21/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= render 'layouts/header' %>
  </head>

  <body>
  	</br>
  	</br>
  	</br>
  	</br>
    <%= yield %>
  </body>
</html>

j21/app/views/static_pages/home.html.erb
<h2>Salut, tu veux connaitre la réponse à la question de l'univers ??</h2>

Si oui, vérifie que tu es bien log, puis clique <%= link_to 'ici', secret_path %> </br>
Si tu veux te login, ca se passe par <%= link_to 'la', login_path %>

j21/app/views/static_pages/secret_page.html.erb
<h1>42</h1>